# - name: Create systemd service file for Kanata
#   copy:
#     dest: "~/.config/systemd/user/kanata.service"
#     content: |
#       [Unit]
#       Description=Kanata keyboard remapper
#       Documentation=https://github.com/jtroo/kanata
#
#       [Service]
#       Environment=PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin
#       Type=simple
#       ExecStart=/usr/bin/sh -c 'exec $(which kanata) --cfg $HOME/.config/kanata/config.kbd'
#       Restart=no
#
#       [Install]
#       WantedBy=default.target
#     mode: '0644'

- name: Reload systemd user daemon
  command: systemctl --user daemon-reload

- name: Enable and start Kanata service
  command: systemctl --user enable --now kanata.service
