- name: Check if cargo is installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.cargo/bin/cargo"
  register: cargo_exists

- include_tasks: base-install.yml
  when: not cargo_exists.stat.exists

- name: Install cargo packages
  community.general.cargo:
    name: "{{ cargo_packages }}"
    state: latest
  environment:
    PATH: "/home/{{ username }}/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
    OPENSSL_NO_VENDOR: "true"
    CRATE_CC_NO_DEFAULTS: "true"
    CARGO_TARGET_DIR: "/tmp/cargo-installmdsRe4"
    CFLAGS: "-fPIE"
  ignore_errors: true
  register: cargo_install_result

- name: installation failed, run the cargo command yourself
  ansible.builtin.debug:
    msg:
      - "`cargo install` seems to have failed, run the command yourself."
      - "cargo install {{ cargo_packages | join(' ') }}"
  when:
    - cargo_install_result is failed

