---
# Stuff with sudo
- hosts: all
  become: true

  roles:
    - role: system
      tags:
        - system
        - software_install

    - role: nvidia_drivers
      tags:
        - system
        - software_install

    - role: dotfiles
      tags:
        - dotfiles

    - role: kanata
      tags:
        - dotfiles

    - role: geerlingguy.docker
      tags:
        - docker

  tasks:
    - import_tasks: tasks/mononoki.yml
      tags: software_install

    - import_tasks: tasks/hosts_blocklist.yml
      tags: system

# Stuff without sudo
- hosts: all

  roles:
    - role: rust
      tags:
        - software_install
        - rust

  tasks:
    - import_tasks: tasks/yazi.yml
      tags:
        - software_install
        - rust
