---
# Stuff with sudo
- hosts: workstations
  become: yes

  roles:
    - role: system
      tags:
        - system

    - role: dotfiles
      tags:
        - dotfiles

    - role: geerlingguy.docker
      tags:
        - docker

# Stuff without sudo
- hosts: workstations

  tasks:
    - import_tasks: tasks/mononoki.yml
      become: yes
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
