---
# Stuff with sudo
- hosts: all
  become: yes

  roles:
    - role: system
      tags:
        - system

    - role: dotfiles
      tags:
        - dotfiles

    - role: geerlingguy.docker
      tags:
        - docker

  tasks:
    - import_tasks: tasks/mononoki.yml

# Stuff without sudo
- hosts: all

  tasks:
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
      tags:
        - rust
