---
# Stuff with sudo
- hosts: workstations
  become: yes

  roles:
    # - role: system
    #   tags:
    #     - system

    # - role: dotfiles
    #   tags:
    #     - dotfiles

    # - role: hyprland
    #   tags:
    #     - hyprland

    - role: geerlingguy.docker
      tags:
        - docker

    - role: kmonad
      tags:
        - kmonad
        - software_install

# Stuff without sudo
- hosts: workstations

  # tasks:
  #   - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
