---
# Stuff with sudo
- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/user.yml

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - update_install

# Stuff without sudo
- hosts: all

  roles:
    - dotfiles

  tasks:
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
    - import_tasks: tasks/install_kmonad.yml
