---
# Stuff with sudo
- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/user.yml

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - update_install

  tasks:
    - import_tasks: tasks/mononoki.yml

# Stuff without sudo
- hosts: all
  become_user: "{{ username }}"

  roles:
    - dotfiles
    - kmonad

  tasks:
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
