---
- hosts: all
  become: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker


- hosts: all

  roles:
    - dotfiles

  tasks:
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
    - import_tasks: tasks/install_kmonad.yml
