---
#
# Tasks and roles for all hosts
#
- hosts: servers
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml
        tags:
            - always
            - port

- hosts: servers
  become: yes

  pre_tasks:
    - import_tasks: tasks/user.yml

  roles:
      - role: system
        tags:
            - system

      - role: dotfiles
        tags:
            - dotfiles

      - role: geerlingguy.security
        tags:
            - security

      - role: geerlingguy.pip
        tags:
            - docker

      - role: geerlingguy.docker
        tags:
            - docker

      # Look into this!!!
      # - role: chriswayg.msmtp-mailer
      #   tags:
      #       - msmtp

      - name: containers
        tags:
          - containers

- hosts: servers
  tasks:
    - import_tasks: tasks/rustup.yml
