---
# SSH juggle port will try to connect with the configured
# user and root.
- name: Juggle SSH port
  hosts: servers
  gather_facts: no
  pre_tasks:
    - name: Import ssh_juggle_port task
      ansible.builtin.import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - always
        - port

# Do the rest of the setup here.

