---
- name: Workstation playbook
  hosts: workstation
  become: true

  roles:
    - role: geerlingguy.docker
      tags: A
    - role: system
      tags: B
    - role: dotfiles
      tags: C
    - role: rust_install
      tags: D

  tasks:
    - name: Blocklist domains
      ansible.builtin.import_tasks: tasks/hosts_blocklist.yml
      tags: E
