---
- name: Workstation playbook
  hosts: workstation
  become: true

  roles:
    - role: geerlingguy.docker
    - role: system
    - role: dotfiles
    - role: rust_install

  tasks:
    - name: Blocklist domains
      ansible.builtin.import_tasks: tasks/hosts_blocklist.yml
