---
# Stuff with sudo
- hosts: workstations
  become: yes

  pre_tasks:
    - import_tasks: tasks/user.yml

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - update_install
    - qemu

  tasks:
    - import_tasks: tasks/mononoki.yml

# Stuff without sudo
- hosts: workstations

  roles:
    - dotfiles
    - kmonad

  tasks:
    - import_tasks: tasks/rustup.yml # important: do not "become: yes" on this task
