---
- name: Workstation playbook
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      tags:
        - docker
        - install

    - role: rust_install
      tags:
        - rust
        - install

    - role: system

  tasks:
    - name: Blocklist domains
      ansible.builtin.import_tasks: tasks/hosts_blocklist.yml
