- name: Check if Mononoki is installed
  ansible.builtin.stat:
    path: "/usr/share/fonts/Mononoki/"
  register: mononoki_exists

- name: Create the Mononoki directory
  ansible.builtin.file:
    path: "/usr/share/fonts/Mononoki/"
    state: directory
    mode: '755'

- name: Download and unarchive Mononoki nerd font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Mononoki.zip
    dest: "/usr/share/fonts/Mononoki/"
    remote_src: true
    mode: '755'
  when: not mononoki_exists.stat.exists
