- name: Check if cargo is installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.cargo/bin/cargo"
  register: cargo_exists

- name: Download Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  when: not cargo_exists.stat.exists

- name: Install rust toolchain
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  when: not cargo_exists.stat.exists

- name: Update rust toolchain
  ansible.builtin.shell: "/home/{{ username }}/.cargo/bin/rustup update"
  when: cargo_exists.stat.exists
  register: result
  changed_when: 'result.stdout is search("updated")'

- name: Add nightly toolchain
  ansible.builtin.shell: "/home/{{ username }}/.cargo/bin/rustup toolchain install nightly"
  register: result
  changed_when: 'result.stdout is search("installed")'

- name: Add wasm target
  ansible.builtin.shell: "/home/{{ username }}/.cargo/bin/rustup target add wasm32-unknown-unknown"
  register: result
  changed_when: 'result.stdout is search("installing")'

- name: Install cargo packages
  community.general.cargo:
    name: "{{ cargo_packages }}"
    state: latest
  environment:
    PATH: "/home/{{ username }}/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
    OPENSSL_NO_VENDOR: true
    CRATE_CC_NO_DEFAULTS: true
    CARGO_TARGET_DIR: "/tmp/cargo-installmdsRe4"
    CFLAGS: "-fPIE"
  ignore_errors: true
  register: _cargo_install_result

- name: run the cargo command yourself
  ansible.builtin.debug:
    msg:
      - "`cargo install` seems to have failed, run the command yourself."
      - "cargo install {{ cargo_packages | join(' ') }}"
  when:
    - _cargo_install_result is failed
