- name: Check if cargo is installed
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_exists

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  when: not cargo_exists.stat.exists

- name: Install rust toolchain
  shell: /tmp/sh.rustup.rs -y
  when: not cargo_exists.stat.exists

- name: Update rust toolchain
  shell: rustup update
  when: cargo_exists.stat.exists
  register: result
  changed_when: 'result.stdout is search("updated")'

- name: Add nightly toolchain
  shell: rustup toolchain install nightly
  register: result
  changed_when: 'result.stdout is search("installed")'

- name: Add wasm target
  shell: rustup target add wasm32-unknown-unknown
  register: result
  changed_when: 'result.stdout is search("installing")'

- name: Install cargo packages
  community.general.cargo:
    name: "{{ cargo_packages }}"
    state: latest
