- name: Check if cargo is installed
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_exists

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  when: not cargo_exists.stat.exists

- name: install rust toolchain
  shell: /tmp/sh.rustup.rs -y
  when: not cargo_exists.stat.exists

- name: install cargo packages
  community.general.cargo:
    name: "{{ cargo_packages }}"
    state: latest
