- name: Clone dotfiles
  ansible.builtin.shell: "git clone {{ dotfiles_url }} /home/{{ username }}/dotfiles"
  become: false

- name: Create directories that we don't want stow to symlink
  file:
    path:
      - "/home/{{ username }}/.config/"
      - "/home/{{ username }}/.local/"
      - "/home/{{ username }}/.local/git"
      - "/home/{{ username }}/.local/bin"
      - "/home/{{ username }}/.config/systemd/user/"
      - "/home/{{ username }}/.cargo/"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Run stow
  loop: "{{ stowed_directories }}"
  ansible.builtin.shell: "stow -d /home/{{ username }}/dotfiles --verbose=2 {{ item }}"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Create the uinput group if it doesn't exist
  ansible.builtin.group:
    name: uinput
    state: present

- name: Add user to uinput group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: uinput
    append: yes
