# - name: Clone my dotfiles on the machine
#   ansible.builtin.git:
#     repo: "{{ dotfiles_url }}"
#     depth: 1
#     key_file: "/home/{{ username }}/.ssh/id_rsa"
#     dest: "/home/{{ username }}/dotfiles"

- name: Run stow
  loop: "{{ stowed_directories }}"
  ansible.builtin.shell: "stow -d /home/{{ username }}/dotfiles --verbose=2 {{ item }}"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Create the uinput group if it doesn't exist
  ansible.builtin.group:
    name: uinput
    state: present

- name: Add user to uinput group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: uinput
    append: yes
