- name: Check if the dotfiles directory exists on the user
  ansible.builtin.stat:
    path: "/home/{{ username }}/dotfiles"
  register: dotfiles_directory

- name: Get dotfiles url value
  ansible.builtin.set_fact:
    dotfiles_url_fact: "{{ dotfiles_url }}"

- name: Generate keypair to add to github account
  ansible.builtin.import_tasks: ssh_keygen.yml
  when: not dotfiles_directory.stat.exists and dotfiles_url_fact is regex('^git\@github.*')
  become: true
  become_user: "{{ username }}"

- name: Clone and stow the dotfiles
  ansible.builtin.import_tasks: folder_managing.yml
  when: not dotfiles_directory.stat.exists
