- name: Check if the dotfiles directory exists on the user
  stat:
    path: "{{ ansible_env.HOME }}/dotfiles"
  register: dotfiles_directory

- name: Generate keypair to add to github account
  import_tasks: ssh_keygen.yml
  when: not dotfiles_directory.stat.exists

- name: Clone and stow the dotfiles
  import_tasks: folder_managing.yml
  when: not dotfiles_directory.stat.exists
