- name: Create the ~/.ssh directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: '0700'

- name: Add github.com to known_hosts
  ansible.builtin.known_hosts:
    path: "/home/{{ username }}/.ssh/known_hosts"
    name: github.com
    key: "{{ lookup('ansible.builtin.file', 'pubkeys/github.com') }}"

- name: Generate an OpenSSH keypair with the default values
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"

- name: Print url and instructions
  ansible.builtin.debug:
    msg:
      - "Please go to the following url: https://github.com/settings/keys"
      - "And add a new SSH key with the following key:"

- name: Get public key
  ansible.builtin.shell: "cat /home/{{ username }}/.ssh/id_rsa.pub"
  register: id_rsa_output
  changed_when: false

- name: Print public key
  ansible.builtin.debug:
    msg: "{{ id_rsa_output.stdout }}"

- name: Pause execution to let the user add the key to github
  ansible.builtin.pause:
    prompt: "The execution is now paused, press enter once you have added the public key to github"
    echo: true
