# System stuff

username: pohl

# The URL at which to get the dotfiles
dotfiles_url: "git@github.com:paul-ohl/dotfiles.git"

# Which directories to stow in the dotfiles repo
# This will also determine whether some software is installed or not
stowed_directories:
  # - alacritty
  - custom_scripts
  - git
  # - hyprland
  - kanata
  - kitty
  - neovim
  - rust
  - zellij
  - zsh

# Install QEMU
qemu_install: false

packages:
  - clang
  - curl
  - flatpak
  - fzf
  - git
  - kitty
  - lld
  - mold
  - neovim
  - nodejs
  - openssl
  - openssl-devel
  - pkg-config
  - stow
  - unzip
  - vim
  - wget
  - zsh

cargo_packages:
  - bacon
  - bat
  - cargo-watch
  - cargo-update
  - du-dust
  - exa
  - kanata
  - ripgrep
  - zellij

flatpak_packages:
  # - org.audacityteam.Audacity
  # - org.blender.Blender
  - com.spotify.Client
  # - com.discordapp.Discord
  - org.filezillaproject.Filezilla
  # - org.gimp.GIMP
  # - org.kde.kdenlive
  - md.obsidian.Obsidian
  - com.getpostman.Postman
  - org.qbittorrent.qBittorrent
  # - com.slack.Slack
  # - com.valvesoftware.Steam
  # - com.github.IsmaelMartinez.teams_for_linux
  # - com.github.micahflee.torbrowser-launcher
  - org.videolan.VLC
  # - us.zoom.Zoom

# Software-specific variables
kmonad_config_name: main.kbd

# Geerlingguy's docker role variables
docker_edition: "ce"
docker_users:
  - "{{ username }}"
