# System stuff

username: astro
shell: /usr/bin/zsh
system_make_user_sudo: true
# passwordless computer, use at your own risk!
system_auto_login_on_boot: true
system_passwordless_sudo: true

# The URL at which to get the dotfiles
dotfiles_url: "git@github.com:paul-ohl/dotfiles.git"
# dotfiles_url: "https://github.com/paul-ohl/dotfiles.git"

# Which directories to stow in the dotfiles repo
# This will also determine whether some software is installed or not
stowed_directories:
  - alacritty
  - custom_scripts
  - git
  # - hyprland
  - kanata
  # - kitty
  - neovim
  - rust
  - tmux
  - zsh

packages:
  - alacritty
  - bat
  - beeper-v4-bin
  - btop
  - curl
  - discord
  - dolphin
  - du-dust
  - duf
  - dunst
  - exa
  - fastfetch
  - feishin
  - firefox
  - fzf
  - git
  - httpie
  - hyprlock
  - kitty
  - lazygit
  - lutris
  - neovim
  - nodejs
  - npm
  - obsidian
  - opencode
  - openssl
  - picard
  - protonup-qt
  - ripgrep
  - steam
  - stow
  - tmux
  - unzip
  - vim
  - vlc
  - vlc-plugins-all
  - waybar
  - wget
  - wofi
  - zsh

cargo_packages:
  - bacon
  - cargo-nextest
  - cargo-update
  - sqlx-cli

# A list of domains to block using the `/etc/hosts` file
blocked_domains:
  - 9gag.com
  - www.9gag.com

# Geerlingguy's docker role variables
docker_edition: "ce"
docker_users:
  - "{{ username }}"
