- name: Update packages
  community.general.pacman:
    update_cache: true
    upgrade: true
    register: result
    changed_when: result.packages | length > 0

- name: Install essential packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install base-devel, required to install paru
  community.general.pacman:
    name: base-devel
    state: present

- name: Make sure destination folder exists
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.local/git/"
    state: directory
    mode: '0744'

- name: Clone paru on the machine
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    depth: 1
    dest: "{{ ansible_env.HOME }}/.local/git/paru"

- name: Install paru
  kewlfft.aur.aur:
    name: paru
    local_pkgbuild: "{{ ansible_env.HOME }}/.local/git/paru"
    use: makepkg
    state: present
  become: true
  become_user: "{{ username }}"
