- name: Update packages
  dnf:
    name: "*"
    state: latest

- name: Install essential packages
  dnf:
    name: "{{ packages }}"
    state: latest

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
