- name: This role is deprecated, use system instead
  ansible.builtin.fail:
    msg: This role is deprecated, use system instead

- name: Install essential packages in Fedora
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  when: ansible_distribution == "Fedora"

- name: Install essential packages in Ubuntu
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
