- name: Update and install in Fedora
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Update and install in Arch Linux
  ansible.builtin.import_tasks: arch.yml
  when: ansible_distribution == "Archlinux" or ansible_distribution == "Arch Linux"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
