---
- name: Update and upgrade packages in Ubuntu
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
  when: ansible_distribution == "Ubuntu"

- name: Install essential packages in Fedora
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest
  when: ansible_distribution == "Fedora"

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install wanted packages
  package:
    name: "{{ packages }}"
    state: present
  when: ansible_distribution == "Ubuntu"
