---
- name: Enable atim's copr for lazygit
  community.general.copr:
    state: enabled
    name: atim/lazygit
  when: ansible_distribution == "Fedora"

- name: Install Lazygit
  ansible.builtin.dnf:
    name: lazygit
    state: latest
  when: ansible_distribution == "Fedora"
