---
- name: Create or modify user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    update_password: "on_create"
    shell: "/usr/bin/zsh"
    groups: 
      - sudo
      - users
    state: present
    append: true

- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0750
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', ssh_public_key) }}"
