- name: Install dependencies
  ansible.builtin.dnf:
    name: stack
    state: present

- name: Make sure build folder exists
  ansible.builtin.file:
    dest: "/home/{{ username }}/.local/git/"
    state: directory
    mode: '0744'

- name: Make sure install folder exists
  ansible.builtin.file:
    dest: "/home/{{ username }}/.local/bin/"
    state: directory
    mode: '0744'

- name: Clone kmonad on the machine
  ansible.builtin.git:
    repo: https://github.com/kmonad/kmonad.git
    depth: 1
    dest: "/home/{{ username }}/.local/git/kmonad"

- name: Build and install kmonad with stack
  ansible.builtin.shell: "(cd /home/{{ username }}/.local/git/kmonad && stack install --local-bin-path /home/{{ username }}/.local/bin/)"

- name: Copy kmonad binary to systemd folder
  ansible.builtin.copy:
    src: "/home/{{ username }}/.local/bin/kmonad"
    dest: /usr/bin/kmonad
    mode: "755"
  become: true

- name: Copy service file to systemd folder
  ansible.builtin.copy:
    src: files/kmonad.service
    dest: /etc/systemd/system/
    mode: "755"
  become: true

- name: Setup systemd
  ansible.builtin.systemd:
    name: kmonad.service
    daemon_reload: true
    enabled: true
    state: started
  become: true
