- name: Make sure build folder exists
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.local/git/kmonad"
    state: directory
    mode: '0744'

- name: Clone kmonad on the machine
  ansible.builtin.git:
    repo: https://github.com/kmonad/kmonad.git
    depth: 1
    dest: "{{ ansible_env.HOME }}/.local/git/kmonad"

- name: Build and install stack
  ansible.builtin.shell: "(cd {{ ansible_env.HOME }}/.local/git/kmonad && stack install --local-bin-path /usr/bin/kmonad)"
  become: true

- name: Copy service file to systemd folder
  ansible.builtin.copy:
    src: "{{ lookup('ansible.builtin.file', 'kmonad.service') }}"
    dest: /etc/systemd/system/
    mode: "755"

- name: Setup systemd
  ansible.builtin.systemd:
    name: kmonad.service
    daemon_reload: true
    enabled: true
    state: started
  become: true
