- name: Check if the kmonad binary exists
  ansible.builtin.stat:
    path: "/usr/bin/kmonad"
  register: binary

- name: Install kmonad on Fedora
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_distribution == "Fedora" and not binary.stat.exists
