# System stuff

username: pohl
password: asdf
domain: paulohl.fr
email: paul.lv.ohl@gmail.com
ssh_public_key: /Users/pohl/.ssh/id_rsa.pub

# Which directories to stow in the dotfiles repo
stowed_directories:
  - custom_scripts
  - git
  - neovim
  - zsh

packages:
  - bat
  - clang
  - curl
  - exa
  - git
  - lld
  - nodejs
  - python3
  - python3-pip
  - ripgrep
  - stow
  - unzip
  - vim
  - wget
  - zsh

dotfiles_url: "https://github.com/paul-ohl/dotfiles.git"

# Docker stuff
docker_dir: /opt/docker/data
docker_compose_dir: /opt/docker/compose
services:
  # - authelia
  # - homer
  - portainer
  # - syncthing
  - vaultwarden

# Geerlingguy's roles:
security_ssh_port: 1251
security_sudoers_passworded: 
  - "{{ username }}"
security_autoupdate_reboot: false
security_autoupdate_reboot_time: '23:00'
  # Once email is set up.
# security_autoupdate_mail_to: '{{ email }}'
# security_autoupdate_mail_on_error: false

pip_install_packages:
  - name: docker
  - name: docker-compose
  - name: pynvim

docker_edition: "ce"
docker_users:
  - "{{ username }}"
