- name: Download Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install rust toolchain
  ansible.builtin.command: /tmp/sh.rustup.rs -y
  changed_when: false

- name: Set default toolchain
  ansible.builtin.command: "/home/{{ username }}/.cargo/bin/rustup default stable"
  changed_when: false

- name: Update rust toolchain
  ansible.builtin.command: "/home/{{ username }}/.cargo/bin/rustup update"
  register: rust_install_result_update
  changed_when: 'rust_install_result_update.stdout is search("updated")'

- name: Add nightly toolchain
  ansible.builtin.command: "/home/{{ username }}/.cargo/bin/rustup toolchain install nightly"
  register: rust_install_result_nightly
  changed_when: 'rust_install_result_nightly.stdout is search("installed")'

- name: Add wasm target
  ansible.builtin.command: "/home/{{ username }}/.cargo/bin/rustup target add wasm32-unknown-unknown"
  register: rust_install_result_wasm
  changed_when: 'rust_install_result_wasm.stdout is search("installing")'
