- include_tasks: install-dependencies.yml
  become: true
  when: not rust_install_packages.empty

- name: Check if cargo is installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.cargo/bin/cargo"
  register: cargo_exists

- include_tasks: base-install.yml
  become: false
  become_user: "{{ username }}"
  when: not cargo_exists.stat.exists and not rust_install_packages.empty

- include_tasks: install-sccache.yml
  become: false
  become_user: "{{ username }}"
  when: rust_install_use_sccache and not rust_install_packages.empty

- include_tasks: install-mold.yml
  become: true
  when: rust_install_use_mold and not rust_install_packages.empty

- name: Install cargo packages
  community.general.cargo:
    name: "{{ rust_install_packages }}"
    state: latest
  environment:
    PATH: "/home/{{ username }}/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
    OPENSSL_NO_VENDOR: "true"
    CRATE_CC_NO_DEFAULTS: "true"
    CARGO_TARGET_DIR: "/tmp/cargo-installmdsRe4"
    CFLAGS: "-fPIE"
    RUSTC_WRAPPER: "/home/{{ username }}/.cargo/bin/sccache"
  ignore_errors: true
  register: cargo_install_result
  when: not rust_install_packages.empty

- name: installation failed, run the cargo command yourself
  ansible.builtin.debug:
    msg:
      - "`cargo install` seems to have failed, run the command yourself."
      - "cargo install {{ cargo_packages | join(' ') }}"
  when:
    - cargo_install_result is failed
