---
- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  pip:
    name: 
      - docker
      - docker-compose

# - name: Install docker module for Python with pipx
#   community.general.pipx:
#     name:
#       - docker
#       - docker-compose

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Copy the compose file
  template: 
    src: templates/compose.yml
    dest: "{{ docker_compose_dir }}/compose.yml"

- name: Copy the Caddy config file
  template: 
    src: templates/Caddyfile
    dest: "{{ docker_dir }}/Caddyfile"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
