networks:
  internal:
    external: true
    name: "internal"

services:
  vaultwarden:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "/start.sh"

    container_name: "vaultwarden"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "ROCKET_ADDRESS=0.0.0.0"
      - "ROCKET_PORT=80"
      - "ROCKET_PROFILE=release"
      - "DOMAIN=https://vault.paulohl.fr"

    hostname: "86b18774437d"

    image: "vaultwarden/server:latest"

    ipc: "private"

    labels:
      org.opencontainers.image.created: "2022-10-14T18:11:03+00:00"
      org.opencontainers.image.documentation: "https://github.com/dani-garcia/vaultwarden/wiki"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.revision: "638766b346dc0e00c5db7935d21e48354d632335"
      org.opencontainers.image.source: "https://github.com/dani-garcia/vaultwarden"
      org.opencontainers.image.url: "https://hub.docker.com/r/vaultwarden/server"
      org.opencontainers.image.version: "1.26.0"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "internal"

    ports:
      - "8002:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "vaultwarden_data:/data"

    working_dir: "/"

version: "3.6"

volumes:
  vaultwarden_data:
    external: true
